### ISSUE TITLE
Bug in nextButtonStyle

### ISSUE THREAD

**Issue by clfristoe** [ardaogulcan/react-native-keyboard-accessory#27]
In the documentation, it states that you can supply a style or stylesheet that will affect the View of the button. When I try and change the style using nextButtonStyle={{height:50}}, I get an invalid prop error: 
<img width="300" alt="portfolio_view" src="https://user-images.githubusercontent.com/15655814/46230255-b6a4d300-c32d-11e8-96e6-4faa20db796f.png">

I have identified that the <AccessoryArrowButton> nextButtonStyle style on line 75 is different than what is used for previousButtonStyle. By change it from:

style={nextButtonStyle && { style: nextButtonStyle }} 

to 
style={nextButtonStyle}

It will allow us to customize height and other style elements for the buttons.

**Comment by ardaogulcan** [comment]
Hi @clfristoe, thank you for noticing this. Looks like it was broken for a long time. It should be fixed in [v0.1.6](https://github.com/ardaogulcan/react-native-keyboard-accessory/releases/tag/0.1.6) with #28. Also, if you are willing to, do not hesitate to open PR if you find any other issues considering we are in hacktoberfest :)
