### ISSUE TITLE
In KeyboardAccessoryView playground(your expo snack), if alwaysVisiable is false, can't see the accessory.

### ISSUE THREAD

**Issue by dazzyjong** [ardaogulcan/react-native-keyboard-accessory#34]
is it expected?

**Comment by ardaogulcan** [comment]
Hey @dazzyjong, yes it is the expected behaviour. KeyboardAccessory is designed to be visible when keyboard is active unless it is stated `alwaysVisible` with props. In that example TextInput is inside the Accessory which is necessary for the the showcase of that use case. If you put TextInput outside when keyboard visible Accessory will also be visible. Please check this example: https://snack.expo.io/@ardaogulcan/c21pbG
